"""WAF detection and fingerprinting module.

Covers ADVANCED_BUGBOUNTY_CVE.md Section 8:
- WAF fingerprinting via headers, cookies, and response patterns
- WAF bypass techniques
- WAF detection tools integration
"""

import json
import os
import re
import subprocess
from pathlib import Path

from rich.console import Console

console = Console()

# WAF signatures
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-connecting-ip"],
        "cookies": ["__cfduid", "cf_clearance"],
        "body_patterns": ["cloudflare", "cf-browser-verification", "cf_chl_opt"],
        "status_codes": [403, 503],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "cookies": ["ak_bmsc", "bm_sv", "akamai_"],
        "body_patterns": ["akamai", "reference #[0-9]"],
        "status_codes": [403],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "cookies": ["aws-waf-token"],
        "body_patterns": ["aws", "x-amzn"],
        "status_codes": [403, 405],
    },
    "Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap_"],
        "body_patterns": ["incapsula", "imperva"],
        "status_codes": [403],
    },
    "ModSecurity": {
        "headers": ["modsecurity", "mod_security"],
        "cookies": [],
        "body_patterns": ["mod_security", "modsecurity", "This error was generated by Mod_Security"],
        "status_codes": [403, 406],
    },
    "F5 BIG-IP ASM": {
        "headers": ["tsessionid"],
        "cookies": ["BIGipServer", "TS"],
        "body_patterns": ["BIGipServer", "F5 Networks"],
        "status_codes": [403],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body_patterns": ["sucuri", "Access Denied"],
        "status_codes": [403],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "cookies": ["barra_counter_session"],
        "body_patterns": ["Barracuda"],
        "status_codes": [403],
    },
    "Imperva": {
        "headers": ["x-iinfo"],
        "cookies": ["incap_ses", "nlbi_"],
        "body_patterns": ["imperva", "incapsula"],
        "status_codes": [403],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfwaf-authcookie", "wordfence_verifiedHuman"],
        "body_patterns": ["wordfence", "Generated by Wordfence"],
        "status_codes": [403],
    },
}


def detect_waf(
    target: str,
    output_dir: str = "./results",
) -> dict:
    """Detect WAF protecting the target.

    Uses header, cookie, and response analysis to identify WAF.

    Args:
        target: Target URL
        output_dir: Output directory
    """
    results = {
        "target": target,
        "method": "waf_detection",
        "waf_detected": False,
        "waf_name": None,
        "waf_details": {},
    }

    os.makedirs(output_dir, exist_ok=True)

    console.print(f"  [dim]Detecting WAF on {target}...[/dim]")

    try:
        import requests

        # Normal request
        resp = requests.get(target, timeout=10, verify=False)
        headers = dict(resp.headers)
        cookies = dict(resp.cookies)
        body = resp.text[:5000]  # Limit body size

        # Check each WAF signature
        for waf_name, signature in WAF_SIGNATURES.items():
            detected = False
            indicators = []

            # Check headers
            for header in signature["headers"]:
                if any(h.lower() == header.lower() for h in headers):
                    detected = True
                    indicators.append(f"Header: {header}")

            # Check cookies
            for cookie in signature["cookies"]:
                if any(c.lower().startswith(cookie.lower()) for c in cookies):
                    detected = True
                    indicators.append(f"Cookie: {cookie}")

            # Check body patterns
            for pattern in signature["body_patterns"]:
                if re.search(pattern, body, re.IGNORECASE):
                    detected = True
                    indicators.append(f"Body pattern: {pattern}")

            if detected:
                results["waf_detected"] = True
                results["waf_name"] = waf_name
                results["waf_details"] = {
                    "name": waf_name,
                    "indicators": indicators,
                }
                console.print(f"  [bold red]⚠ WAF detected: {waf_name}[/bold red]")
                for indicator in indicators:
                    console.print(f"    [red]{indicator}[/red]")
                break

        # Also try wafw00f for detection
        try:
            cmd = ["wafw00f", target, "-o", "-", "-f", "json"]
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)

            if result.returncode == 0:
                try:
                    waf_data = json.loads(result.stdout)
                    if waf_data and "firewall" in str(waf_data):
                        console.print(f"  [cyan]wafw00f detected: {waf_data}[/cyan]")
                except json.JSONDecodeError:
                    pass
        except FileNotFoundError:
            pass
        except subprocess.TimeoutExpired:
            pass

        if not results["waf_detected"]:
            console.print(f"  [green]✓ No WAF detected on {target}[/green]")

    except requests.RequestException as e:
        console.print(f"  [yellow]Request failed: {e}[/yellow]")

    # Save results
    output_file = Path(output_dir) / "waf_detection.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)

    console.print(f"  [dim]Results saved to {output_file}[/dim]")
    return results


def fingerprint_waf(
    target: str,
    output_dir: str = "./results",
) -> dict:
    """Fingerprint WAF version and configuration.

    Args:
        target: Target URL
        output_dir: Output directory
    """
    results = {
        "target": target,
        "method": "waf_fingerprint",
        "waf_name": None,
        "version": None,
        "details": {},
    }

    os.makedirs(output_dir, exist_ok=True)

    console.print(f"  [dim]Fingerprinting WAF on {target}...[/dim]")

    try:
        import requests

        # Send various requests to fingerprint WAF
        resp = requests.get(target, timeout=10, verify=False)

        # Check for version information in headers
        version_headers = {
            "X-Powered-By": "X-Powered-By",
            "Server": "Server",
            "X-AspNet-Version": "X-AspNet-Version",
        }

        for header_name, header_key in version_headers.items():
            if header_key in resp.headers:
                results["details"][header_name] = resp.headers[header_key]

        # Check response body for version info
        body = resp.text[:5000]
        version_patterns = [
            re.compile(r'(?i)waf[:\s]+v?(\d+\.\d+[\.\d]*)'),
            re.compile(r'(?i)firewall[:\s]+v?(\d+\.\d+[\.\d]*)'),
        ]

        for pattern in version_patterns:
            match = pattern.search(body)
            if match:
                results["version"] = match.group(1)
                break

    except requests.RequestException as e:
        console.print(f"  [yellow]Request failed: {e}[/yellow]")

    # Save results
    output_file = Path(output_dir) / "waf_fingerprint.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)

    return results


def test_waf_bypass(
    target: str,
    output_dir: str = "./results",
) -> dict:
    """Test common WAF bypass techniques.

    Args:
        target: Target URL
        output_dir: Output directory
    """
    results = {
        "target": target,
        "method": "waf_bypass",
        "techniques": [],
    }

    os.makedirs(output_dir, exist_ok=True)

    console.print(f"  [dim]Testing WAF bypass techniques on {target}...[/dim]")

    bypass_techniques = [
        # Case variation
        {"name": "case_variation", "payload": "<ScRiPt>alert(1)</ScRiPt>"},
        # Double encoding
        {"name": "double_encoding", "payload": "%253Cscript%253Ealert(1)%253C/script%253E"},
        # Unicode
        {"name": "unicode", "payload": "\u003cscript\u003ealert(1)\u003c/script\u003e"},
        # Null bytes
        {"name": "null_bytes", "payload": "<scri%00pt>alert(1)</scri%00pt>"},
        # Case-insensitive
        {"name": "mixed_case", "payload": "<sCrIpT>alert(1)</ScRiPt>"},
    ]

    try:
        import requests

        for technique in bypass_techniques:
            try:
                # Test with payload in URL
                test_url = f"{target}?test={technique['payload']}"
                resp = requests.get(test_url, timeout=10, verify=False)

                # Check if payload was reflected
                if technique["payload"] in resp.text:
                    results["techniques"].append({
                        "name": technique["name"],
                        "success": True,
                        "status_code": resp.status_code,
                    })
                    console.print(f"    [red]✗ {technique['name']}: Payload reflected[/red]")
                else:
                    results["techniques"].append({
                        "name": technique["name"],
                        "success": False,
                        "status_code": resp.status_code,
                    })
            except Exception:
                continue

    except requests.RequestException as e:
        console.print(f"  [yellow]Request failed: {e}[/yellow]")

    successful = [t for t in results["techniques"] if t["success"]]
    if successful:
        console.print(f"  [bold red]⚠ {len(successful)} bypass techniques worked[/bold red]")
    else:
        console.print(f"  [green]✓ No bypass techniques succeeded[/green]")

    # Save results
    output_file = Path(output_dir) / "waf_bypass.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)

    return results


def scan_waf(
    target: str,
    output_dir: str = "./results",
) -> dict:
    """Run full WAF scan.

    Args:
        target: Target URL
        output_dir: Output directory
    """
    results = {
        "target": target,
        "method": "waf_full",
        "detection": {},
        "fingerprint": {},
        "bypass": {},
    }

    os.makedirs(output_dir, exist_ok=True)

    console.print(f"[bold]  Running full WAF scan on {target}[/bold]")

    results["detection"] = detect_waf(target, output_dir)
    results["fingerprint"] = fingerprint_waf(target, output_dir)
    results["bypass"] = test_waf_bypass(target, output_dir)

    # Save merged results
    merged_file = Path(output_dir) / "waf_full.json"
    with open(merged_file, "w") as f:
        json.dump(results, f, indent=2)

    return results
