"""Report generation module."""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from rich.console import Console

console = Console()

REPORT_TEMPLATE = """# Security Assessment Report

**Target:** {target}
**Date:** {date}
**Tool:** bountykit v0.1
**Analyst:** [Authorized Security Researcher]

---

## Executive Summary

This report summarizes the findings from the security assessment conducted against **{target}**.

**Total Findings:** {total_findings}
- 🔴 Critical: {critical}
- 🟠 High: {high}
- 🟡 Medium: {medium}
- 🔵 Low: {low}
- ⚪ Info: {info}

---

## Findings

{findings_section}

---

## Methodology

The following tools and techniques were used during this assessment:

{tools_used}

---

## Recommendations

Based on the findings, the following actions are recommended:

{recommendations}

---

## Disclaimer

This assessment was conducted with proper authorization. All testing was performed
in a non-destructive manner. The findings and recommendations in this report are
provided for remediation purposes only.

---

*Report generated by bountykit — Advanced Bug Bounty & CVE Research CLI*
"""


def generate_report(
    input_dir: str,
    fmt: str = "markdown",
    output: Optional[str] = None,
) -> str:
    """Generate a consolidated report from scan results.

    Args:
        input_dir: Directory containing scan results
        fmt: Output format (markdown or json)
        output: Output file path
    """
    console.print(f"\n[bold cyan]Generating Report[/bold cyan]")
    console.print(f"  Input: {input_dir}")
    console.print(f"  Format: {fmt}\n")

    # Collect all results
    results = _collect_results(input_dir)

    if not results:
        console.print("[yellow]No results found to generate report.[/yellow]")
        return ""

    # Count findings by severity
    all_findings = []
    for result in results:
        all_findings.extend(result.get("findings", []))

    severity_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
    for finding in all_findings:
        sev = finding.get("severity", "INFO").upper()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    # Get tools used
    tools_used = set()
    for result in results:
        tools_used.add(result.get("tool", "unknown"))

    # Generate report
    if fmt == "markdown":
        report_content = _generate_markdown(
            results,
            all_findings,
            severity_counts,
            tools_used,
        )
    else:
        report_content = json.dumps({
            "results": results,
            "summary": severity_counts,
            "tools": list(tools_used),
        }, indent=2)

    # Save report
    if not output:
        output = f"./report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{ 'md' if fmt == 'markdown' else 'json'}"

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        f.write(report_content)

    console.print(f"[green]✓ Report saved to {output_path}[/green]\n")
    return str(output_path)


def _collect_results(input_dir: str) -> list:
    """Collect all JSON result files from a directory."""
    results = []
    path = Path(input_dir)

    if not path.exists():
        return results

    for json_file in path.glob("*.json"):
        try:
            with open(json_file) as f:
                data = json.load(f)
                if isinstance(data, dict):
                    results.append(data)
        except (json.JSONDecodeError, IOError):
            continue

    return results


def _generate_markdown(
    results: list,
    all_findings: list,
    severity_counts: dict,
    tools_used: set,
) -> str:
    """Generate markdown report content."""
    findings_section = ""

    if all_findings:
        for i, finding in enumerate(all_findings, 1):
            sev = finding.get("severity", "info").upper()
            sev_icon = {
                "CRITICAL": "🔴",
                "HIGH": "🟠",
                "MEDIUM": "🟡",
                "LOW": "🔵",
                "INFO": "⚪",
            }.get(sev, "⚪")

            findings_section += f"### Finding {i}: {finding.get('type', 'Unknown')}\n\n"
            findings_section += f"- **Severity:** {sev_icon} {sev}\n"
            findings_section += f"- **Detail:** {finding.get('detail', 'N/A')}\n"

            if finding.get("url"):
                findings_section += f"- **URL:** {finding['url']}\n"

            if finding.get("evidence"):
                findings_section += f"- **Evidence:** `{finding['evidence'][:100]}`\n"

            findings_section += "\n"
    else:
        findings_section = "No significant findings detected.\n"

    tools_list = "\n".join(f"- {tool}" for tool in tools_used)

    recommendations = _generate_recommendations(all_findings)

    return REPORT_TEMPLATE.format(
        target=results[0].get("target", "N/A") if results else "N/A",
        date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        total_findings=len(all_findings),
        critical=severity_counts.get("CRITICAL", 0),
        high=severity_counts.get("HIGH", 0),
        medium=severity_counts.get("MEDIUM", 0),
        low=severity_counts.get("LOW", 0),
        info=severity_counts.get("INFO", 0),
        findings_section=findings_section,
        tools_used=tools_list,
        recommendations=recommendations,
    )


def _generate_recommendations(findings: list) -> str:
    """Generate recommendations based on findings."""
    recommendations = []
    severity_types = set()

    for finding in findings:
        sev = finding.get("severity", "").upper()
        severity_types.add(sev)

    if "CRITICAL" in severity_types:
        recommendations.append("1. **Immediate Action Required:** Address all critical severity issues immediately.")
        recommendations.append("2. Review and restrict cloud metadata endpoint access.")

    if "HIGH" in severity_types:
        recommendations.append("3. Address high severity issues within 30 days.")
        recommendations.append("4. Implement proper access controls and authentication.")

    if "MEDIUM" in severity_types:
        recommendations.append("5. Address medium severity issues within 90 days.")
        recommendations.append("6. Review and update security configurations.")

    if not recommendations:
        recommendations.append("1. Continue monitoring for new vulnerabilities.")
        recommendations.append("2. Regular security assessments are recommended.")

    return "\n".join(recommendations)
