"""Report generation utilities for BountyKit.

Generates HTML and Markdown reports from scan findings,
CVE data, and exploit search results.
"""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional, Any

from rich.console import Console

console = Console()

SEVERITY_COLORS = {
    "critical": "#dc2626",
    "high": "#ea580c",
    "medium": "#d97706",
    "low": "#2563eb",
    "info": "#6b7280",
}

SEVERITY_EMOJI = {
    "critical": "\u2716",
    "high": "\u26a0",
    "medium": "\u25cf",
    "low": "\u2139",
    "info": "\u2022",
}


def generate_markdown_report(
    target: str,
    findings: List[dict],
    output_path: str = "./results/report.md",
    title: str = "BountyKit Security Report",
    extra_sections: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate a Markdown report from findings.

    Args:
        target: Target that was scanned
        findings: List of finding dicts with 'severity', 'title', 'description'
        output_path: Where to write the report
        title: Report title
        extra_sections: Additional sections to include

    Returns:
        Path to the generated report
    """
    os.makedirs(Path(output_path).parent, exist_ok=True)

    # Build severity counts
    severity_counts = {}
    for f in findings:
        sev = f.get("severity", "info").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    lines = [
        f"# {title}",
        "",
        f"**Target:** `{target}`  ",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  ",
        f"**Findings:** {len(findings)}  ",
        "",
        "## Summary",
        "",
    ]

    # Severity summary table
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["critical", "high", "medium", "low", "info"]:
        count = severity_counts.get(sev, 0)
        if count > 0:
            emoji = SEVERITY_EMOJI.get(sev, "")
            lines.append(f"| {emoji} {sev.capitalize()} | {count} |")
    lines.append("")

    # Risk assessment
    risk_score = _calculate_risk(findings)
    risk_label = "Low"
    if risk_score >= 70:
        risk_label = "Critical"
    elif risk_score >= 50:
        risk_label = "High"
    elif risk_score >= 30:
        risk_label = "Medium"

    lines.append(f"**Risk Score:** {risk_score:.1f}/100 ({risk_label})  ")
    lines.append("")

    # Findings detail
    if findings:
        lines.append("## Findings")
        lines.append("")

        # Sort by severity
        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        sorted_findings = sorted(
            findings,
            key=lambda f: severity_order.get(f.get("severity", "info").lower(), 5),
        )

        for i, f in enumerate(sorted_findings, 1):
            sev = f.get("severity", "info").lower()
            emoji = SEVERITY_EMOJI.get(sev, "")
            lines.append(f"### {i}. {emoji} {f.get('title', 'Untitled Finding')}")
            lines.append("")
            lines.append(f"- **Severity:** {sev.capitalize()}")
            if f.get("cwe"):
                lines.append(f"- **CWE:** {f['cwe']}")
            if f.get("url"):
                lines.append(f"- **URL:** {f['url']}")
            if f.get("source"):
                lines.append(f"- **Source:** {f['source']}")
            lines.append("")
            lines.append(f"> {f.get('description', 'No description provided.')}")
            lines.append("")
            if f.get("fix"):
                lines.append(f"**Fix:** {f['fix']}")
                lines.append("")

    # Extra sections
    if extra_sections:
        for section_title, section_content in extra_sections.items():
            lines.append(f"## {section_title}")
            lines.append("")
            if isinstance(section_content, str):
                lines.append(section_content)
            elif isinstance(section_content, list):
                for item in section_content:
                    if isinstance(item, dict):
                        for k, v in item.items():
                            lines.append(f"- **{k}:** {v}")
                    else:
                        lines.append(f"- {item}")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by BountyKit v0.2.0 on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

    content = "\n".join(lines)

    with open(output_path, "w") as f:
        f.write(content)

    console.print(f"  [green]Report saved to {output_path}[/green]")
    return output_path


def generate_html_report(
    target: str,
    findings: List[dict],
    output_path: str = "./results/report.html",
    title: str = "BountyKit Security Report",
    extra_sections: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate an HTML report from findings.

    Args:
        target: Target that was scanned
        findings: List of finding dicts
        output_path: Where to write the report
        title: Report title
        extra_sections: Additional sections to include

    Returns:
        Path to the generated report
    """
    os.makedirs(Path(output_path).parent, exist_ok=True)

    severity_counts = {}
    for f in findings:
        sev = f.get("severity", "info").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    risk_score = _calculate_risk(findings)
    risk_label = "Low"
    risk_color = "#2563eb"
    if risk_score >= 70:
        risk_label = "Critical"
        risk_color = "#dc2626"
    elif risk_score >= 50:
        risk_label = "High"
        risk_color = "#ea580c"
    elif risk_score >= 30:
        risk_label = "Medium"
        risk_color = "#d97706"

    # Build findings rows
    findings_html = ""
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_findings = sorted(
        findings,
        key=lambda f: severity_order.get(f.get("severity", "info").lower(), 5),
    )

    for i, f in enumerate(sorted_findings, 1):
        sev = f.get("severity", "info").lower()
        color = SEVERITY_COLORS.get(sev, "#6b7280")
        findings_html += f"""
        <tr>
            <td>{i}</td>
            <td><span style="color:{color};font-weight:bold">{sev.upper()}</span></td>
            <td><strong>{_escape_html(f.get('title', 'Untitled'))}</strong><br>
                <small>{_escape_html(f.get('description', ''))}</small></td>
            <td>{f.get('cwe', '')}</td>
            <td>{f.get('source', '')}</td>
        </tr>"""

    # Extra sections HTML
    extra_html = ""
    if extra_sections:
        for section_title, content in extra_sections.items():
            extra_html += f"<h2>{_escape_html(section_title)}</h2>\n"
            if isinstance(content, str):
                extra_html += f"<pre>{_escape_html(content)}</pre>\n"
            elif isinstance(content, list):
                extra_html += "<ul>\n"
                for item in content:
                    if isinstance(item, dict):
                        items_text = "; ".join(f"{k}: {v}" for k, v in item.items())
                        extra_html += f"<li>{_escape_html(items_text)}</li>\n"
                    else:
                        extra_html += f"<li>{_escape_html(str(item))}</li>\n"
                extra_html += "</ul>\n"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{_escape_html(title)}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #0f172a; color: #e2e8f0; line-height: 1.6; padding: 2rem; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ color: #38bdf8; font-size: 1.8rem; margin-bottom: 0.5rem; }}
        h2 {{ color: #7dd3fc; font-size: 1.3rem; margin: 1.5rem 0 0.5rem; }}
        .meta {{ color: #94a3b8; font-size: 0.9rem; margin-bottom: 1.5rem; }}
        .summary {{ display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 1.5rem; }}
        .card {{ background: #1e293b; border-radius: 8px; padding: 1rem 1.5rem;
                 border-left: 4px solid #334155; min-width: 140px; }}
        .card-label {{ font-size: 0.8rem; color: #94a3b8; text-transform: uppercase; }}
        .card-value {{ font-size: 1.5rem; font-weight: bold; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; }}
        th, td {{ text-align: left; padding: 0.6rem 0.8rem; border-bottom: 1px solid #1e293b; }}
        th {{ background: #1e293b; color: #94a3b8; font-size: 0.8rem;
              text-transform: uppercase; position: sticky; top: 0; }}
        tr:hover {{ background: #1e293b; }}
        small {{ color: #94a3b8; }}
        pre {{ background: #1e293b; padding: 1rem; border-radius: 6px;
               overflow-x: auto; font-size: 0.85rem; }}
        .footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #1e293b;
                   color: #64748b; font-size: 0.8rem; }}
    </style>
</head>
<body>
<div class="container">
    <h1>{_escape_html(title)}</h1>
    <div class="meta">
        Target: <code>{_escape_html(target)}</code> &middot;
        Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} &middot;
        Findings: {len(findings)}
    </div>

    <div class="summary">
        <div class="card">
            <div class="card-label">Risk Score</div>
            <div class="card-value" style="color:{risk_color}">{risk_score:.0f}</div>
            <div class="card-label">{risk_label}</div>
        </div>
        <div class="card">
            <div class="card-label">Critical</div>
            <div class="card-value" style="color:{SEVERITY_COLORS['critical']}">
                {severity_counts.get('critical', 0)}</div>
        </div>
        <div class="card">
            <div class="card-label">High</div>
            <div class="card-value" style="color:{SEVERITY_COLORS['high']}">
                {severity_counts.get('high', 0)}</div>
        </div>
        <div class="card">
            <div class="card-label">Medium</div>
            <div class="card-value" style="color:{SEVERITY_COLORS['medium']}">
                {severity_counts.get('medium', 0)}</div>
        </div>
        <div class="card">
            <div class="card-label">Low</div>
            <div class="card-value" style="color:{SEVERITY_COLORS['low']}">
                {severity_counts.get('low', 0)}</div>
        </div>
    </div>

    <h2>Findings</h2>
    <table>
        <thead>
            <tr><th>#</th><th>Severity</th><th>Description</th><th>CWE</th><th>Source</th></tr>
        </thead>
        <tbody>
            {findings_html if findings_html else '<tr><td colspan="5" style="text-align:center;color:#64748b">No findings</td></tr>'}
        </tbody>
    </table>

    {extra_html}

    <div class="footer">
        Generated by BountyKit v0.2.0 on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    </div>
</div>
</body>
</html>"""

    with open(output_path, "w") as f:
        f.write(html)

    console.print(f"  [green]HTML report saved to {output_path}[/green]")
    return output_path


def generate_json_report(
    target: str,
    findings: List[dict],
    output_path: str = "./results/report.json",
    extra_data: Optional[Dict[str, Any]] = None,
) -> str:
    """Generate a JSON report from findings.

    Args:
        target: Target that was scanned
        findings: List of finding dicts
        output_path: Where to write the report
        extra_data: Additional data to include

    Returns:
        Path to the generated report
    """
    os.makedirs(Path(output_path).parent, exist_ok=True)

    severity_counts = {}
    for f in findings:
        sev = f.get("severity", "info").lower()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    report = {
        "target": target,
        "generated_at": datetime.now().isoformat(),
        "tool": "BountyKit v0.2.0",
        "summary": {
            "total_findings": len(findings),
            "by_severity": severity_counts,
            "risk_score": _calculate_risk(findings),
        },
        "findings": findings,
    }

    if extra_data:
        report.update(extra_data)

    with open(output_path, "w") as f:
        json.dump(report, f, indent=2, default=str)

    console.print(f"  [green]JSON report saved to {output_path}[/green]")
    return output_path


def _calculate_risk(findings: List[dict]) -> float:
    """Calculate overall risk score from findings."""
    if not findings:
        return 0.0

    weights = {"critical": 10.0, "high": 7.0, "medium": 4.0, "low": 1.0, "info": 0.0}
    total = 0.0
    for f in findings:
        sev = f.get("severity", "info").lower()
        total += weights.get(sev, 0.0)

    # Normalize to 0-100 scale (assume max ~30 findings)
    return min(total / 30.0 * 100, 100.0)


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#x27;")
    )
