"""WAF detection, fingerprinting, and bypass module.

Covers 2026 WAF techniques:
- Advanced WAF fingerprinting (10+ WAFs)
- DataCenter/IP detection (Cloudflare, AWS, Akamai, Fastly)
- AI/ML-based WAF detection (Cloudflare AI, AWS WAF with AI)
- 2026 bypass techniques (Unicode, chunked, mutation, HTTP/2 smuggling)
- WAF-specific bypass methods
"""

import json
import os
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

from bountykit.utils.logger import get_logger

logger = get_logger(__name__)

# ─── 2026 WAF Signatures ────────────────────────────────────────────────────

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-connecting-ip", "cf-visitor"],
        "cookies": ["__cfduid", "cf_clearance", "__cflb", "__cf_bm"],
        "body_patterns": [
            "cloudflare", "cf-browser-verification", "cf_chl_opt",
            "cf-error-detail", "Attention Required! | Cloudflare"
        ],
        "status_codes": [403, 503],
        "error_pages": ["cloudflare.com/errors", "Cloudflare"],
        "datacenter": {
            "headers": ["cf-ray", "cf-connecting-ip", "cf-ipcountry"],
            "provider": "Cloudflare",
            "pop_locations": ["SFO", "LAX", "NYC", "LHR", "FRA", "NRT"],
        },
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id", "x-akamai-session-info"],
        "cookies": ["ak_bmsc", "bm_sv", "akamai_", "_abck", "akamai_"],
        "body_patterns": ["akamai", "reference #[0-9]", "Access Denied"],
        "status_codes": [403],
        "error_pages": ["AkamaiGHost", "Reference #[0-9]+"],
        "datacenter": {
            "headers": ["x-akamai-transformed"],
            "provider": "Akamai",
            "pop_locations": ["US-E", "US-W", "EU", "APAC"],
        },
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
        "cookies": ["aws-waf-token"],
        "body_patterns": ["aws", "x-amzn", "aws-waf-token"],
        "status_codes": [403, 405],
        "error_pages": ["AWS WAF", "x-amzn"],
        "ai_features": ["AWS WAF with AWS Shield", "AWS Shield Advanced"],
    },
    "Incapsula/Imperva": {
        "headers": ["x-iinfo", "x-cdn", "x-protected-by"],
        "cookies": ["incap_ses", "visid_incap_", "nlbi_", "reese84"],
        "body_patterns": ["incapsula", "imperva", "Access Denied by Incapsula"],
        "status_codes": [403],
        "error_pages": ["incapsula.com", "imperva.com"],
        "ai_features": ["Imperva Bot Management", "Imperva Adaptive Security"],
    },
    "ModSecurity": {
        "headers": ["modsecurity", "mod_security"],
        "cookies": [],
        "body_patterns": [
            "mod_security", "modsecurity",
            "This error was generated by Mod_Security",
            "ModSecurity Action"
        ],
        "status_codes": [403, 406, 501],
        "error_pages": ["ModSecurity", "modsecurity"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["tsessionid"],
        "cookies": ["BIGipServer", "TS", "BIGipServers"],
        "body_patterns": ["BIGipServer", "F5 Networks", "Request Rejected"],
        "status_codes": [403],
        "error_pages": ["F5 Networks", "BIG-IP"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body_patterns": ["sucuri", "Access Denied", "Sucuri WebSite Firewall"],
        "status_codes": [403],
        "error_pages": ["sucuri.net", "Sucuri"],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "cookies": ["barra_counter_session"],
        "body_patterns": ["Barracuda", "Barracuda Web Application Firewall"],
        "status_codes": [403],
        "error_pages": ["barracuda.com"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfwaf-authcookie", "wordfence_verifiedHuman"],
        "body_patterns": [
            "wordfence", "Generated by Wordfence",
            "This response contains AI-generated content"
        ],
        "status_codes": [403, 503],
        "ai_features": ["Wordfence AI Threat Detection"],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "x-fastly-debug-path", "x-served-by"],
        "cookies": [],
        "body_patterns": ["Fastly error", "fastly"],
        "status_codes": [403],
        "datacenter": {
            "headers": ["x-served-by", "x-fastly-request-id"],
            "provider": "Fastly",
        },
    },
    "Vercel": {
        "headers": ["x-vercel-id", "x-vercel-cache"],
        "cookies": ["__vercel_insights_id"],
        "body_patterns": ["Vercel", "502: BAD_GATEWAY"],
        "status_codes": [403],
    },
    "Netlify": {
        "headers": ["x-nf-request-id"],
        "cookies": ["nf_did", "netlify_identity"],
        "body_patterns": ["Netlify", "Page not found"],
        "status_codes": [404, 502],
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-fd-healthprobe"],
        "cookies": [],
        "body_patterns": ["Azure Front Door", "Microsoft Azure"],
        "status_codes": [403],
    },
    "Google Cloud Armor": {
        "headers": ["x-goog-generation", "x-goog-metageneration"],
        "cookies": [],
        "body_patterns": ["Google Cloud Armor", "denied by Security Policy"],
        "status_codes": [403],
    },
    "Radware": {
        "headers": ["x-sl-chain-id"],
        "cookies": ["RadwareBotManager"],
        "body_patterns": ["Radware", "Bot Manager"],
        "status_codes": [403],
    },
    "Reblaze": {
        "headers": ["x-reblaze-id"],
        "cookies": ["reblaze_"],
        "body_patterns": ["Reblaze", "Access denied"],
        "status_codes": [403],
    },
    "Wallarm": {
        "headers": ["x-wallarm-id"],
        "cookies": [],
        "body_patterns": ["Wallarm", "blocked by Wallarm"],
        "status_codes": [403],
    },
    "Shape Security": {
        "headers": [],
        "cookies": ["shape"],
        "body_patterns": ["Shape Security"],
        "status_codes": [403],
    },
    "DataDome": {
        "headers": ["x-datadome-clientid"],
        "cookies": ["datadome"],
        "body_patterns": ["DataDome", "blocked by DataDome"],
        "status_codes": [403],
        "ai_features": ["DataDome AI-powered bot protection"],
    },
    "PerimeterX/HUMAN": {
        "headers": ["x-px"],
        "cookies": ["_pxhd", "px3", "pxvid"],
        "body_patterns": ["PerimeterX", "HUMAN Security"],
        "status_codes": [403],
        "ai_features": ["HUMAN Bot Defender"],
    },
}

# ─── DataCenter Detection Signatures ────────────────────────────────────────

DATACENTER_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-connecting-ip", "cf-ipcountry"],
        "asn_prefix": "AS13335",
        "ranges": ["173.245.48.0/20", "103.21.244.0/22", "103.22.200.0/22"],
    },
    "AWS CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop"],
        "asn_prefix": "AS16509",
        "ranges": ["13.32.0.0/12", "13.35.0.0/16"],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "x-served-by"],
        "asn_prefix": "AS54113",
        "ranges": ["151.101.0.0/16"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed"],
        "asn_prefix": "AS20940",
        "ranges": ["23.0.0.0/12", "23.32.0.0/11"],
    },
    "Google Cloud": {
        "headers": ["x-goog-generation"],
        "asn_prefix": "AS15169",
        "ranges": ["34.0.0.0/8", "35.190.0.0/12"],
    },
    "Microsoft Azure": {
        "headers": ["x-msedge-ref", "x-azure-ref"],
        "asn_prefix": "AS8075",
        "ranges": ["13.64.0.0/11", "40.64.0.0/10"],
    },
}


@dataclass
class WAFFinding:
    """WAF detection finding."""

    waf_name: str
    detected: bool
    indicators: list[str] = field(default_factory=list)
    bypass_techniques: list[str] = field(default_factory=list)
    datacenter: Optional[str] = None
    ai_features: list[str] = field(default_factory=list)
    severity: str = "info"
    confidence: str = "medium"
    details: str = ""


@dataclass
class WAFResult:
    """Complete WAF scan result."""

    target: str
    findings: list[WAFFinding] = field(default_factory=list)
    waf_detected: bool = False
    waf_name: Optional[str] = None
    datacenter: Optional[str] = None
    bypasses_found: int = 0
    scan_duration: float = 0.0
    errors: list[str] = field(default_factory=list)


class WAFScanner:
    """Advanced WAF scanner with 2026 techniques."""

    def __init__(
        self,
        target: str,
        output_dir: str = "./results",
        timeout: int = 15,
        verify_ssl: bool = False,
    ):
        self.target = target.rstrip("/")
        self.output_dir = output_dir
        self.timeout = timeout
        self.verify_ssl = verify_ssl
        self.findings: list[WAFFinding] = []
        self.session = httpx.Client(
            timeout=timeout,
            verify=verify_ssl,
            follow_redirects=True,
            http2=True,
        )
        os.makedirs(output_dir, exist_ok=True)

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(min=2, max=10))
    def _send_request(self, url: str, method: str = "GET", **kwargs) -> httpx.Response:
        """Send HTTP request with retry."""
        return self.session.request(method, url, **kwargs)

    def detect_waf(self) -> WAFFinding:
        """Detect WAF using header, cookie, and body analysis."""
        logger.info(f"Detecting WAF on {self.target}")

        try:
            resp = self._send_request(self.target)
            headers = dict(resp.headers)
            cookies = dict(resp.cookies)
            body = resp.text[:10000]

            for waf_name, signature in WAF_SIGNATURES.items():
                indicators = []

                # Check headers
                for header in signature["headers"]:
                    if any(h.lower() == header.lower() for h in headers):
                        indicators.append(f"Header: {header}")

                # Check cookies
                for cookie in signature["cookies"]:
                    if any(c.lower().startswith(cookie.lower()) for c in cookies):
                        indicators.append(f"Cookie: {cookie}")

                # Check body patterns
                for pattern in signature["body_patterns"]:
                    if re.search(pattern, body, re.IGNORECASE):
                        indicators.append(f"Body: {pattern}")

                # Check status codes
                if resp.status_code in signature.get("status_codes", []):
                    indicators.append(f"Status: {resp.status_code}")

                # Check error pages
                for error_page in signature.get("error_pages", []):
                    if re.search(error_page, body, re.IGNORECASE):
                        indicators.append(f"ErrorPage: {error_page}")

                if indicators:
                    confidence = "high" if len(indicators) >= 3 else "medium" if len(indicators) >= 2 else "low"

                    finding = WAFFinding(
                        waf_name=waf_name,
                        detected=True,
                        indicators=indicators,
                        confidence=confidence,
                        ai_features=signature.get("ai_features", []),
                        details=f"Detected via {len(indicators)} indicators",
                    )
                    self.findings.append(finding)
                    logger.info(f"WAF detected: {waf_name} (confidence: {confidence})")
                    return finding

            # No WAF detected
            finding = WAFFinding(
                waf_name="None",
                detected=False,
                details="No WAF detected via signature analysis",
            )
            self.findings.append(finding)
            return finding

        except Exception as e:
            logger.error(f"WAF detection failed: {e}")
            finding = WAFFinding(
                waf_name="Unknown",
                detected=False,
                details=f"Detection failed: {str(e)}",
            )
            self.findings.append(finding)
            return finding

    def detect_datacenter(self) -> Optional[str]:
        """Detect datacenter/cloud provider."""
        logger.info(f"Detecting datacenter for {self.target}")

        try:
            resp = self._send_request(self.target)
            headers = dict(resp.headers)

            for provider, sig in DATACENTER_SIGNATURES.items():
                for header in sig["headers"]:
                    if header.lower() in [h.lower() for h in headers]:
                        logger.info(f"Datacenter detected: {provider}")
                        return provider

            return None

        except Exception as e:
            logger.error(f"Datacenter detection failed: {e}")
            return None

    def test_bypasses(self) -> list[WAFFinding]:
        """Test 2026 WAF bypass techniques."""
        logger.info(f"Testing WAF bypass techniques on {self.target}")

        bypass_techniques = [
            # ─── 2026 Bypass Techniques ─────────────────────────────
            {"name": "unicode_normalization", "payload": "\u003cscript\u003ealert(1)\u003c/script\u003e"},
            {"name": "chunked_encoding", "payload": "Transfer-Encoding: chunked"},
            {"name": "http2_smuggle", "payload": ":method: GET\r\n:path: /admin\r\n"},
            {"name": "case_variation", "payload": "<ScRiPt>alert(1)</ScRiPt>"},
            {"name": "double_encoding", "payload": "%253Cscript%253Ealert(1)%253C/script%253E"},
            {"name": "null_bytes", "payload": "<scri%00pt>alert(1)</scri%00pt>"},
            {"name": "mixed_case", "payload": "<sCrIpT>alert(1)</ScRiPt>"},
            {"name": "html_comments", "payload": "<script<!-- -->alert(1)</script>"},
            {"name": "mutation_xss", "payload": '<noscript><p title="</noscript><script>alert(1)</script>'},
            {"name": "polyglot", "payload": "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcLiCk=alert() )//"},
            {"name": "json_injection", "payload": '{"__proto__":{"polluted":true}}'},
            {"name": "template_injection", "payload": "{{7*7}}${7*7}<%= 7*7 %>"},
            {"name": "waf_fingerprint_leak", "payload": "GET /%00 HTTP/1.1\r\nHost: a"},
        ]

        bypass_findings = []

        for technique in bypass_techniques:
            try:
                # Test with URL parameter
                test_url = f"{self.target}?test={technique['payload']}"
                resp = self._send_request(test_url)

                # Check if payload was reflected
                if technique["payload"] in resp.text:
                    finding = WAFFinding(
                        waf_name="Bypass",
                        detected=True,
                        indicators=[f"Technique: {technique['name']}"],
                        bypass_techniques=[technique["name"]],
                        severity="high",
                        confidence="high",
                        details=f"Payload reflected via {technique['name']}",
                    )
                    bypass_findings.append(finding)
                    logger.warning(f"Bypass found: {technique['name']}")

                # Test with header injection
                if "header" in technique.get("payload", "").lower():
                    try:
                        resp2 = self._send_request(
                            self.target,
                            headers={"X-Test": technique["payload"]},
                        )
                        if resp2.status_code == 200:
                            finding = WAFFinding(
                                waf_name="Bypass",
                                detected=True,
                                indicators=[f"Header technique: {technique['name']}"],
                                bypass_techniques=[technique["name"]],
                                severity="high",
                                confidence="medium",
                                details=f"Header injection via {technique['name']}",
                            )
                            bypass_findings.append(finding)
                    except Exception:
                        pass

            except Exception as e:
                logger.debug(f"Bypass test failed for {technique['name']}: {e}")
                continue

        self.findings.extend(bypass_findings)
        return bypass_findings

    def fingerprint_waf(self) -> dict:
        """Fingerprint WAF version and configuration."""
        logger.info(f"Fingerprinting WAF on {self.target}")

        fingerprint = {
            "version": None,
            "headers": {},
            "body_signatures": [],
            "configuration": {},
        }

        try:
            resp = self._send_request(self.target)

            # Check for version information in headers
            version_headers = {
                "X-Powered-By": "X-Powered-By",
                "Server": "Server",
                "X-AspNet-Version": "X-AspNet-Version",
                "X-Generator": "X-Generator",
            }

            for header_name, header_key in version_headers.items():
                if header_key in resp.headers:
                    fingerprint["headers"][header_name] = resp.headers[header_key]

            # Check response body for version info
            body = resp.text[:10000]
            version_patterns = [
                re.compile(r'(?i)waf[:\s]+v?(\d+\.\d+[\.\d]*)'),
                re.compile(r'(?i)firewall[:\s]+v?(\d+\.\d+[\.\d]*)'),
                re.compile(r'(?i)version[:\s]+(\d+\.\d+[\.\d]*)'),
            ]

            for pattern in version_patterns:
                match = pattern.search(body)
                if match:
                    fingerprint["version"] = match.group(1)
                    break

            # Check for security headers
            security_headers = [
                "strict-transport-security",
                "content-security-policy",
                "x-frame-options",
                "x-content-type-options",
                "x-xss-protection",
                "referrer-policy",
            ]

            for header in security_headers:
                if header in [h.lower() for h in resp.headers]:
                    fingerprint["configuration"][header] = resp.headers.get(header, "present")

        except Exception as e:
            logger.error(f"WAF fingerprinting failed: {e}")

        return fingerprint

    def run_full_scan(self) -> WAFResult:
        """Run full WAF scan with all techniques."""
        import time
        start_time = time.time()

        logger.info(f"Running full WAF scan on {self.target}")

        result = WAFResult(target=self.target)

        # 1. Detect WAF
        waf_finding = self.detect_waf()
        result.waf_detected = waf_finding.detected
        result.waf_name = waf_finding.waf_name

        # 2. Detect datacenter
        result.datacenter = self.detect_datacenter()

        # 3. Fingerprint WAF
        fingerprint = self.fingerprint_waf()

        # 4. Test bypasses
        bypass_findings = self.test_bypasses()
        result.bypasses_found = len(bypass_findings)

        # 5. Compile results
        result.findings = self.findings
        result.scan_duration = time.time() - start_time

        # 6. Save results
        self._save_results(result)

        return result

    def _save_results(self, result: WAFResult):
        """Save scan results."""
        output_file = Path(self.output_dir) / "waf_scan.json"

        with open(output_file, "w") as f:
            json.dump(
                {
                    "target": result.target,
                    "waf_detected": result.waf_detected,
                    "waf_name": result.waf_name,
                    "datacenter": result.datacenter,
                    "bypasses_found": result.bypasses_found,
                    "scan_duration": result.scan_duration,
                    "findings": [
                        {
                            "waf_name": f.waf_name,
                            "detected": f.detected,
                            "indicators": f.indicators,
                            "bypass_techniques": f.bypass_techniques,
                            "severity": f.severity,
                            "confidence": f.confidence,
                            "details": f.details,
                        }
                        for f in result.findings
                    ],
                },
                f,
                indent=2,
            )

        logger.info(f"Results saved to {output_file}")


# ─── Legacy Functions ────────────────────────────────────────────────────────

def detect_waf(target: str, output_dir: str = "./results") -> dict:
    """Legacy WAF detection function."""
    scanner = WAFScanner(target, output_dir)
    finding = scanner.detect_waf()
    return {
        "target": target,
        "waf_detected": finding.detected,
        "waf_name": finding.waf_name,
        "indicators": finding.indicators,
    }


def fingerprint_waf(target: str, output_dir: str = "./results") -> dict:
    """Legacy WAF fingerprint function."""
    scanner = WAFScanner(target, output_dir)
    return scanner.fingerprint_waf()


def test_waf_bypass(target: str, output_dir: str = "./results") -> dict:
    """Legacy WAF bypass function."""
    scanner = WAFScanner(target, output_dir)
    findings = scanner.test_bypasses()
    return {
        "target": target,
        "bypasses_found": len(findings),
        "techniques": [
            {"name": f.bypass_techniques[0], "success": True}
            for f in findings
            if f.bypass_techniques
        ],
    }


def scan_waf(target: str, output_dir: str = "./results") -> dict:
    """Legacy full WAF scan function."""
    scanner = WAFScanner(target, output_dir)
    result = scanner.run_full_scan()
    return {
        "target": result.target,
        "waf_detected": result.waf_detected,
        "waf_name": result.waf_name,
        "bypasses_found": result.bypasses_found,
        "findings_count": len(result.findings),
    }
